/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayouthomeIndexRouteImport } from './routes/_layout/(home)/index'
import { Route as LayouthomeIdRouteImport } from './routes/_layout/(home)/$id'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayouthomeIndexRoute = LayouthomeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayouthomeIdRoute = LayouthomeIdRouteImport.update({
  id: '/(home)/$id',
  path: '/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayouthomeIndexRoute
  '/$id': typeof LayouthomeIdRoute
}
export interface FileRoutesByTo {
  '/$id': typeof LayouthomeIdRoute
  '/': typeof LayouthomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/(home)/$id': typeof LayouthomeIdRoute
  '/_layout/(home)/': typeof LayouthomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/$id' | '/'
  id: '__root__' | '/_layout' | '/_layout/(home)/$id' | '/_layout/(home)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/(home)/': {
      id: '/_layout/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayouthomeIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/(home)/$id': {
      id: '/_layout/(home)/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof LayouthomeIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayouthomeIdRoute: typeof LayouthomeIdRoute
  LayouthomeIndexRoute: typeof LayouthomeIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayouthomeIdRoute: LayouthomeIdRoute,
  LayouthomeIndexRoute: LayouthomeIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
